-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 06:44:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gestioninventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestioninventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestioninventario` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gestioninventario` ;

-- -----------------------------------------------------
-- Table `gestioninventario`.`almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`almacen` (
  `id_almacen` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `ubicacion` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`id_almacen`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestioninventario`.`detalle_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`detalle_factura` (
  `id_detalle` INT NOT NULL,
  `id_transaccion` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_detalle`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestioninventario`.`detalle_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`detalle_producto` (
  `id_producto` INT NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `stock` INT NOT NULL,
  `id_almacen` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `id_almacen` (`id_almacen` ASC) VISIBLE,
  CONSTRAINT `detalle_producto_ibfk_1`
    FOREIGN KEY (`id_almacen`)
    REFERENCES `gestioninventario`.`almacen` (`id_almacen`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestioninventario`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `stock` INT NOT NULL,
  `id_almacen` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  UNIQUE INDEX `codigo` (`codigo` ASC) VISIBLE,
  INDEX `id_almacen` (`id_almacen` ASC) VISIBLE,
  CONSTRAINT `producto_ibfk_1`
    FOREIGN KEY (`id_almacen`)
    REFERENCES `gestioninventario`.`almacen` (`id_almacen`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestioninventario`.`transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`transacciones` (
  `id_transaccion` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `total` DECIMAL(10,2) NOT NULL,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`id_transaccion`),
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `transacciones_ibfk_1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `gestioninventario`.`producto` (`id_producto`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestioninventario`.`detalle_transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`detalle_transaccion` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_transaccion` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_detalle`),
  INDEX `id_transaccion` (`id_transaccion` ASC) VISIBLE,
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `detalle_transaccion_ibfk_1`
    FOREIGN KEY (`id_transaccion`)
    REFERENCES `gestioninventario`.`transacciones` (`id_transaccion`)
    ON DELETE CASCADE,
  CONSTRAINT `detalle_transaccion_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `gestioninventario`.`producto` (`id_producto`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestioninventario`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`factura` (
  `id_detalle` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_detalle`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestioninventario`.`producto_lista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`producto_lista` (
  `id_producto` INT NOT NULL,
  `codigo` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `stock` INT NOT NULL,
  `id_almacen` INT NOT NULL,
  PRIMARY KEY (`id_producto`, `id_almacen`),
  UNIQUE INDEX `codigo` (`codigo` ASC, `id_almacen` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestioninventario`.`producto_nombre_precio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`producto_nombre_precio` (
  `id_producto` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestioninventario`.`producto_pmayor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`producto_pmayor` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `stock` INT NOT NULL,
  `id_almacen` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  UNIQUE INDEX `codigo` (`codigo` ASC) VISIBLE,
  INDEX `id_almacen` (`id_almacen` ASC) VISIBLE,
  CONSTRAINT `producto_pmayor_ibfk_1`
    FOREIGN KEY (`id_almacen`)
    REFERENCES `gestioninventario`.`almacen` (`id_almacen`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestioninventario`.`producto_pmenor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`producto_pmenor` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `stock` INT NOT NULL,
  `id_almacen` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  UNIQUE INDEX `codigo` (`codigo` ASC) VISIBLE,
  INDEX `id_almacen` (`id_almacen` ASC) VISIBLE,
  CONSTRAINT `producto_pmenor_ibfk_1`
    FOREIGN KEY (`id_almacen`)
    REFERENCES `gestioninventario`.`almacen` (`id_almacen`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestioninventario`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestioninventario`.`transacciones_fecha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`transacciones_fecha` (
  `id_transaccion` INT NOT NULL,
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`id_transaccion`),
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `transacciones_fecha_ibfk_1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `gestioninventario`.`producto` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestioninventario`.`transacciones_rango`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`transacciones_rango` (
  `id_transaccion` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `total` DECIMAL(10,2) NOT NULL,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`id_transaccion`, `fecha`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci PARTITION BY RANGE(year(`fecha`)) PARTITIONS 3( PARTITION p_2023 VALUES LESS THAN (2024),  PARTITION p_2024 VALUES LESS THAN (2025),  PARTITION p_2025 VALUES LESS THAN (2026)) ;


-- -----------------------------------------------------
-- Table `gestioninventario`.`transacciones_total`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`transacciones_total` (
  `id_transaccion` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_transaccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestioninventario`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `psswrd` VARCHAR(100) NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `id_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `gestioninventario`.`roles` (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestioninventario`.`usuarios_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestioninventario`.`usuarios_data` (
  `id_usuario` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `psswrd` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `gestioninventario`;

DELIMITER $$
USE `gestioninventario`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `gestioninventario`.`calcular_total_venta`
BEFORE INSERT ON `gestioninventario`.`transacciones`
FOR EACH ROW
begin
    declare precio_unitario decimal(10,2);

    -- Obtiene el precio del producto --
    select precio into precio_unitario
    from Producto
    where id_producto = NEW.id_producto;

    -- Calcula el total de la venta --
    set NEW.total = NEW.cantidad * precio_unitario;
end$$

USE `gestioninventario`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `gestioninventario`.`actualizar_stock`
AFTER INSERT ON `gestioninventario`.`detalle_transaccion`
FOR EACH ROW
begin
    update Producto 
    set stock = stock - NEW.cantidad
    where id_producto = NEW.id_producto;
end$$

USE `gestioninventario`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `gestioninventario`.`verificar_stock`
BEFORE INSERT ON `gestioninventario`.`detalle_transaccion`
FOR EACH ROW
begin
    declare stock_actual int;

    -- Obtiene el stock disponible del producto --
    select stock into stock_actual
    from Producto
    where id_producto = NEW.id_producto;

    -- Verifica si hay suficiente stock --
    if stock_actual < NEW.cantidad then
        signal sqlstate '45000'
        set message_text = 'Error: Stock insuficiente para realizar la venta';
    end if;
end$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
